name: Build and Deploy Our Web Application

on: 
  push:
    branches:
      - master
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 => Checkout Branch
      uses: actions/checkout@master
      
    - name: Step 2 => Setup nuget cli
      uses: nuget/setup-nuget@v1.0.5
      
    - name: Step 3 => Steup .net sdk
      uses: actions/setup-dotnet@v1.4.0
      continue-on-error: false
      
    - name: Step 4 => publish 
      run: dotnet publish ./Demo-WebApp-2021/ -c Release
      continue-on-error: false
      
    - name: Step 5 => Upload Artifcat
      uses: actions/upload-artifact@v1.0.0
      with: 
        name: v1
        path: ./Demo-WebApp-22021/bin/Release/net5.0/publish
      continue-on-error: false
    
    - name: publish the app
      uses: azure/webapps-deploy@v2
      with:
        app-name: azurebootcamp2021
        publish-profile: ${{ secrets.APPPUBLISH }}
        package: './Demo-WebApp-22021/bin/Release/net5.0/publish'

      
